package nbastats

import "github.com/tlowerison/nbastats/model"

var (
  college = model.ArgEnum{
    Name:    "College",
    Options: []string{
      "High School",
      "No College",
      "---",
      "Acadia (CAN)",
      "Adams State",
      "Adelphi",
      "Air Force",
      "Akron",
      "Alabama",
      "Alabama A&M",
      "Alabama-Birmingham",
      "Alabama-Huntsville",
      "Alabama State",
      "Albany",
      "Albany State (GA)",
      "Alcorn State",
      "Alliance",
      "American",
      "American International",
      "Angelo State",
      "Appalachian State",
      "Arizona",
      "Arizona State",
      "Arkansas",
      "Arkansas-Fort Smith",
      "Arkansas-Little Rock",
      "Arkansas-Pine Bluff",
      "Arkansas State",
      "Army",
      "Assumption",
      "Auburn",
      "Auburn-Montgomery",
      "Augsburg",
      "Augustana (IL)",
      "Augustana (SD)",
      "Augusta State",
      "Aurora",
      "Austin Peay",
      "Averett",
      "Azusa Pacific",
      "Ball State",
      "Baltimore",
      "Barton",
      "Barton Community College",
      "Baylor",
      "Belmont",
      "Belmont Abbey",
      "Beloit",
      "Bemidji State",
      "Benedict",
      "Bethel (TN)",
      "Binghamton",
      "Biola",
      "Blinn",
      "Bloomfield",
      "Bloomsburg",
      "Bluefield",
      "Boise State",
      "Boston College",
      "Boston University",
      "Bowie State",
      "Bowling Green",
      "Bradley",
      "Brevard Community College",
      "Brewton-Parker",
      "Bridgeport",
      "Brigham Young",
      "Brigham Young-Hawaii",
      "Brooklyn",
      "Brown",
      "Bryant",
      "Bucknell",
      "Buffalo",
      "Buffalo State",
      "Butler",
      "Butler Community College",
      "C.W. Post",
      "California",
      "California (PA)",
      "California-Berkeley",
      "California-Davis",
      "California-Irvine",
      "California-Los Angeles",
      "California-Riverside",
      "California-Santa Barbara",
      "Cal State-Bakersfield",
      "Cal State-Dominguez Hills",
      "Cal State-Fullerton",
      "Cal State-Los Angeles",
      "Cal State-Northridge",
      "Cal State-Poly Pomona",
      "Cal State-San Bernardino",
      "Campbell",
      "Campbellsville",
      "Canisius",
      "Case Western",
      "Catholic",
      "Centenary (LA)",
      "Central Arkansas",
      "Central Connecticut State",
      "Central Florida",
      "Central Michigan",
      "Central Missouri",
      "Central Oklahoma",
      "Central State (OH)",
      "Central Washington",
      "Charleston (WV)",
      "Cheyney",
      "Chicago State",
      "Christopher Newport",
      "Cincinnati",
      "City College of New York",
      "Claflin",
      "Clark Atlanta",
      "Clayton State",
      "Clemson",
      "Cleveland State",
      "Colgate",
      "College of Charleston",
      "College of New Jersey",
      "Colorado",
      "Colorado Christian",
      "Colorado State",
      "Colorado State-Pueblo",
      "Columbia",
      "Columbus State",
      "Concordia",
      "Concordia-Irvine",
      "Connecticut",
      "Coppin State",
      "Cornell",
      "Corpus Christi",
      "Creighton",
      "Culver-Stockton",
      "Dakota Wesleyan",
      "Dartmouth",
      "Davidson",
      "Davis & Elkins",
      "Dayton",
      "Delaware",
      "Delaware State",
      "Delta State",
      "Denver",
      "DePaul",
      "DePauw",
      "Detroit Mercy",
      "Dillard",
      "District of Columbia",
      "Drake",
      "Drexel",
      "Duke",
      "Duquesne",
      "East Carolina",
      "East Central",
      "Eastern Illinois",
      "Eastern Kentucky",
      "Eastern Michigan",
      "Eastern New Mexico",
      "Eastern Oklahoma State (Junior College)",
      "Eastern Washington",
      "East Tennessee State",
      "Eckerd",
      "Elizabeth City State",
      "Elon",
      "Evangel",
      "Evansville",
      "Fairfield",
      "Fairleigh Dickinson",
      "Fayetteville State",
      "Ferris State",
      "Findlay",
      "Florida",
      "Florida A&M",
      "Florida Atlantic",
      "Florida Community College",
      "Florida Gulf Coast",
      "Florida International",
      "Florida State",
      "Fordham",
      "Fort Valley State",
      "Franklin",
      "Fresno State",
      "Friends",
      "Furman",
      "Gannon",
      "Gardner-Webb",
      "George Mason",
      "Georgetown",
      "Georgetown College",
      "George Washington",
      "Georgia",
      "Georgia Southern",
      "Georgia State",
      "Georgia Tech",
      "Gonzaga",
      "Grambling",
      "Grand Canyon",
      "Green Bay",
      "Grinnell College",
      "Guilford",
      "Hamline",
      "Hampton",
      "Hardin-Simmons",
      "Hartford",
      "Harvard",
      "Hawaii",
      "High Point",
      "Hillsborough Community College",
      "Hillsdale",
      "Hofstra",
      "Holy Cross",
      "Holy Family",
      "Houston",
      "Houston Baptist",
      "Howard",
      "Humboldt State",
      "Huntington",
      "Idaho",
      "Idaho State",
      "Illinois",
      "Illinois-Chicago",
      "Illinois State",
      "Illinois Wesleyan",
      "Incarnate Word",
      "Indiana",
      "Indianapolis",
      "Indiana Purdue-Fort Wayne",
      "Indiana Purdue-Indianapolis",
      "Indiana State",
      "Indiana Tech",
      "Indian Hills Community College",
      "Iona",
      "Iowa",
      "Iowa State",
      "Jackson State",
      "Jacksonville",
      "Jacksonville State",
      "James Madison",
      "Johnson C. Smith",
      "Kansas",
      "Kansas State",
      "Kennesaw State",
      "Kent State",
      "Kentucky",
      "Kentucky State",
      "Kentucky Wesleyan",
      "Kenyon",
      "King's (NY)",
      "Lafayette",
      "Lamar",
      "La Salle",
      "Lawrence Tech",
      "Lebanon Valley",
      "Lee",
      "Lehigh",
      "Le Moyne",
      "Lewis",
      "Liberty",
      "Lincoln (MO)",
      "Lipscomb",
      "Long Beach State",
      "Long Island-Brooklyn",
      "Longwood",
      "Los Angeles Community College",
      "Louisiana-Lafayette",
      "Louisiana-Monroe",
      "Louisiana State",
      "Louisiana Tech",
      "Louisville",
      "Loyola-Chicago",
      "Loyola-Maryland",
      "Loyola-Marymount",
      "Maine",
      "Manhattan",
      "Marist",
      "Marquette",
      "Marshall",
      "Maryland",
      "Maryland-Eastern Shore",
      "Massachusetts",
      "Master's",
      "McNeese State",
      "Memphis",
      "Mercer",
      "Meridian Community College",
      "Merrimack",
      "Metro State",
      "Miami (FL)",
      "Miami (OH)",
      "Michigan",
      "Michigan State",
      "Middle Tennessee State",
      "Midland",
      "Midwestern State",
      "Miles",
      "Millersville",
      "Minnesota",
      "Minnesota-Duluth",
      "Minnesota State-Mankato",
      "Mississippi",
      "Mississippi Gulf Community College",
      "Mississippi State",
      "Mississippi Valley State",
      "Missouri",
      "Missouri-Kansas City",
      "Missouri State",
      "Missouri Western State",
      "Monmouth",
      "Montana",
      "Montana State",
      "Montevallo",
      "Morehead State",
      "Morehouse",
      "Morgan State",
      "Mountain State",
      "Mount St. Mary's",
      "Mount Union",
      "Mt. San Antonio",
      "Muhlenberg",
      "Murray State",
      "Navy",
      "Nebraska",
      "Nebraska-Kearney",
      "Nebraska-Omaha",
      "Nevada",
      "Nevada-Las Vegas",
      "Nevada-Reno",
      "New Jersey Institute of Technology",
      "New Mexico",
      "New Mexico Highlands",
      "New Mexico State",
      "New Mexico Tech",
      "New Orleans",
      "New York University",
      "Niagara",
      "Nicholls State",
      "Norfolk State",
      "North Carolina",
      "North Carolina A&T",
      "North Carolina-Asheville",
      "North Carolina Central",
      "North Carolina-Charlotte",
      "North Carolina-Greensboro",
      "North Carolina State",
      "North Carolina-Wilmington",
      "North Dakota",
      "North Dakota State",
      "Northeastern",
      "Northeastern State",
      "Northeast Mississippi Community College",
      "Northern Arizona",
      "Northern Colorado",
      "Northern Illinois",
      "Northern Iowa",
      "Northern Kentucky",
      "North Park",
      "North Texas",
      "Northwestern",
      "Northwestern Oklahoma",
      "Northwestern Oklahoma State",
      "Northwestern State",
      "Northwest Florida State",
      "Northwest Nazarene",
      "Northwood",
      "Notre Dame",
      "Oakland",
      "Ohio",
      "Ohio State",
      "Ohio Wesleyan",
      "Oklahoma",
      "Oklahoma Baptist",
      "Oklahoma City",
      "Oklahoma Science and Arts",
      "Oklahoma State",
      "Oklahoma Wesleyan",
      "Old Dominion",
      "Oral Roberts",
      "Oregon",
      "Oregon State",
      "Ouachita Baptist",
      "Pacific",
      "Paine",
      "Penn State",
      "Pennsylvania",
      "Pennsylvania-Kutztown",
      "Pepperdine",
      "Pfeiffer",
      "Phillips",
      "Pikeville",
      "Pittsburgh",
      "Portland",
      "Portland State",
      "Potsdam",
      "Prairie View A&M",
      "Princeton",
      "Providence",
      "Puget Sound",
      "Purdue",
      "Queens (NY)",
      "Quincy",
      "Rhode Island",
      "Rice",
      "Richmond",
      "Rider",
      "Robert Morris (IL)",
      "Rochester (NY)",
      "Rockhurst",
      "Rutgers",
      "Sacramento State",
      "Sacred Heart",
      "Saginaw Valley",
      "Saint Augustine's",
      "Saint Francis (PA)",
      "Saint Joseph's",
      "Saint Louis",
      "Saint Mary's (CA)",
      "Saint Mary's (MN)",
      "Saint Peter's",
      "Saint Rose",
      "Saint Vincent",
      "Salem International",
      "Sam Houston State",
      "San Diego",
      "San Diego State",
      "San Francisco",
      "San Jose State",
      "Santa Clara",
      "Scranton",
      "Seattle",
      "Seton Hall",
      "Seward County Community College",
      "Shaw",
      "Shippensburg",
      "Siena",
      "Slippery Rock",
      "South Alabama",
      "South Carolina",
      "South Carolina-Aiken",
      "South Carolina State",
      "South Carolina Upstate",
      "South Dakota",
      "South Dakota State",
      "Southeastern Illinois",
      "Southeastern Louisiana",
      "Southeastern Oklahoma State",
      "Southeast Missouri State",
      "Southern",
      "Southern California",
      "Southern Illinois",
      "Southern Methodist",
      "Southern Mississippi",
      "Southern Nazarene",
      "Southern Utah",
      "South Florida",
      "Southwest Baptist",
      "Springfield",
      "St. Ambrose",
      "St. Anselm",
      "St. Bonaventure",
      "St. Cloud State",
      "St. Francis Brooklyn",
      "St. John's (NY)",
      "St. Mary's (CA)",
      "St. Mary's (TX)",
      "St. Peter's",
      "St. Thomas (FL)",
      "Stanford",
      "Stephen F. Austin",
      "Stetson",
      "Stony Brook",
      "Syracuse",
      "Tampa",
      "Tarleton State",
      "Temple",
      "Tennessee",
      "Tennessee-Chattanooga",
      "Tennessee-Martin",
      "Tennessee State",
      "Tennessee Tech",
      "Texas",
      "Texas A&M",
      "Texas A&M-Commerce",
      "Texas A&M-Corpus Christi",
      "Texas-Arlington",
      "Texas Christian",
      "Texas-El Paso",
      "Texas-Pan American",
      "Texas-San Antonio",
      "Texas Southern",
      "Texas State",
      "Texas Tech",
      "Texas Wesleyan",
      "Thomas More",
      "Toledo",
      "Towson",
      "Trinity Valley Community College",
      "Troy State",
      "Truman State",
      "Tulane",
      "Tulsa",
      "Tuskegee",
      "UCLA",
      "Utah",
      "Utah State",
      "Utah Valley",
      "Valdosta State",
      "Valparaiso",
      "Vanderbilt",
      "Venezuela",
      "Vermont",
      "Villanova",
      "Virginia",
      "Virginia Commonwealth",
      "Virginia Military Institute",
      "Virginia Tech",
      "Virginia Union",
      "Voorhees",
      "Vorhees",
      "Wake Forest",
      "Walsh",
      "Washington",
      "Washington & Jefferson",
      "Washington State",
      "Wayne State (MI)",
      "Weber State",
      "Western Carolina",
      "Western Illinois",
      "Western Kentucky",
      "Western Michigan",
      "Western Washington",
      "West Florida",
      "West Georgia",
      "Westminster (PA)",
      "West Texas A&M",
      "West Virginia",
      "West Virginia State",
      "West Virginia Tech",
      "West Virginia Wesleyan",
      "Wheaton (IL)",
      "Whitworth",
      "Wichita State",
      "Wilberforce",
      "William & Mary",
      "William Jessup",
      "William Paterson",
      "William Penn",
      "Wingate",
      "Winona State",
      "Winston-Salem State",
      "Winthrop (SC)",
      "Wisconsin",
      "Wisconsin-Eau Claire",
      "Wisconsin-Green Bay",
      "Wisconsin-Milwaukee",
      "Wisconsin-Parkside",
      "Wisconsin-River Falls",
      "Wisconsin-Stevens Point",
      "Wisconsin-Whitewater",
      "Wofford",
      "Wooster",
      "Wright State",
      "Wyoming",
      "Xavier",
      "Xavier (LA)",
      "Yale",
      "Yonsei (KOR)",
      "Youngstown State",
    },
  }
  conference = model.ArgEnum{
    Name:    "Conference",
    Options: []string{"East", "West"},
  }
  counter = model.ArgInt{
    Name:   "Counter",
    Default: 2160,
    Min:     model.IntPtr(1),
    Max:     model.IntPtr(10000),
  }
  country = model.ArgEnum{
    Name:    "Country",
    Options: []string{
      "International",
      "Angola",
      "Argentina",
      "Australia",
      "Belize",
      "Boznia & Herzegovina",
      "Brazil",
      "Cameroon",
      "Canada",
      "China",
      "Congo",
      "Croatia",
      "Czech Republic",
      "Democratic Republic of Congo",
      "Dominican Republic",
      "England",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Great Britain",
      "Greece",
      "Haiti",
      "Iran",
      "Ireland",
      "Israel",
      "Italy",
      "Jamaica",
      "Latvia",
      "Lithuania",
      "Macedonia",
      "Mali",
      "Mexico",
      "Montenegro",
      "Netherlands",
      "New Zealand",
      "Nigeria",
      "Panama",
      "Poland",
      "Puerto Rico",
      "Russia",
      "Scotland",
      "Senegal",
      "Serbia",
      "Serbia and Montenegro",
      "Slovenia",
      "South Korea",
      "Spain",
      "St. Vincent & Grenadines",
      "Sudan",
      "Sudan (UK)",
      "Sweden",
      "Switzerland",
      "Tanzania",
      "Turkey",
      "U.S. Virgin Islands",
      "Ukraine",
      "Uruguay",
      "USA",
      "USSR",
      "Venezuela",
      "Yugoslavia",
    },
  }
  dateFrom = model.ArgDateTime{
    Name: "DateFrom",
  }
  dayOffset = model.ArgInt{
    Name:   "DayOffset",
    Min:     model.IntPtr(0),
  }
  dateTo = model.ArgDateTime{
    Name: "DateTo",
  }
  direction = model.ArgEnum{
    Name:    "Direction",
    Default: "DESC",
    Options: []string{"DESC", "ASC"},
  }
  division = model.ArgEnum{
    Name:    "Division",
    Options: []string{
      "Atlantic",
      "Central",
      "Northwest",
      "Pacific",
      "Southeast",
      "Southwest",
      "East",
      "West",
    },
  }
  draftPick = model.ArgEnum{
    Name:    "DraftPick",
    Options: []string{
      "All Draft Rounds",
      "1st Round",
      "2nd Round",
      "1st Pick",
      "Lottery Pick",
      "Top 5 Pick",
      "Top 10 Pick",
      "Top 15 Pick",
      "Top 20 Pick",
      "Top 25 Pick",
      "Picks 11 Thru 20",
      "Picks 21 Thru 30",
      "Undrafted",
    },
  }
  draftYear = model.ArgInt{
    Name: "DraftYear",
    Min:  model.IntPtr(1947),
    Max:  model.IntPtr(2020),
  }
  endPeriod = model.ArgInt{
    Name:    "EndPeriod",
    Min:     model.IntPtr(0),
    Max:     model.IntPtr(4),
  }
  gameDate = model.ArgDateTime{
    Name: "GameDate",
  }
  gameID = model.ArgString{
    Name: "GameID",
  }
  gameScope = model.ArgString{
    Name: "GameScope",
  }
  gameSegment = model.ArgEnum{
    Name:    "GameSegment",
    Options: []string{
      "First Half",
      "Second Half",
      "Overtime",
    },
  }
  groupQuantity = model.ArgInt{
    Name:    "GroupQuantity",
    Default: 5,
    Min:     model.IntPtr(2),
    Max:     model.IntPtr(5),
  }
  height = model.ArgEnum{
    Name:    "Height",
    Options: []string{
      "< 6-0",
      "> 6-0",
      "< 6-4",
      "> 6-4",
      "< 6-7",
      "> 6-7",
      "< 6-10",
      "> 6-10",
      "< 7-0",
      "> 7-0",
    },
  }
  isOnlyCurrentSeason = model.ArgEnum{
    Name: "IsOnlyCurrentSeason",
    Default: "Y",
    Options: []string{"Y", "N"},
  }
  lastNGames = model.ArgInt{
    Name: "LastNGames",
    Min:  model.IntPtr(0),
    Max:  model.IntPtr(2147483647),
  }
  leagueID = model.ArgEnum{
    Name:    "LeagueID",
    Default: "00",
    Options: []string{"00", "20"},
  }
  location = model.ArgEnum{
    Name: "Location",
    Options: []string{"Home", "Road"},
  }
  measureType = model.ArgEnum{
    Name: "MeasureType",
    Default: "Base",
    Options: []string{
      "Base",
      "Advanced",
      "Defense",
      "Four Factors",
      "Misc",
      "Opponent",
      "Scoring",
      "Usage",
    },
  }
  month = model.ArgInt{
    Name: "Month",
    Min:  model.IntPtr(0),
    Max:  model.IntPtr(12),
  }
  opponentTeamID = model.ArgString{
    Name:    "OpponentTeamID",
    Default: "0",
  }
  outcome = model.ArgEnum{
    Name:    "Outcome",
    Options: []string{"W", "L"},
  }
  pORound = model.ArgInt{
    Name: "PORound",
    Min:  model.IntPtr(0),
    Max:  model.IntPtr(4),
  }
  paceAdjust = model.ArgEnum{
    Name:    "PaceAdjust",
    Default: "N",
    Options: []string{"Y", "N"},
  }
  perMode = model.ArgEnum{
    Name:    "PerMode",
    Default: "PerGame",
    Options: []string{
      "Totals",
      "MinutesPer",
      "PerGame",
      "Per48",
      "Per40",
      "Per36",
      "PerMinute",
      "PerPossession",
      "PerPlay",
      "Per100Possessions",
      "Per100Plays",
    },
  }
  period = model.ArgInt{
    Name: "Period",
    Min:  model.IntPtr(0),
    Max:  model.IntPtr(4),
  }
  playerExperience = model.ArgEnum{
    Name: "PlayerExperience",
    Options: []string{
      "Rookie",
      "Sophomore",
      "Veteran",
    },
  }
  playerPosition = model.ArgEnum{
    Name: "PlayerPosition",
    Options: []string{
      "Center",
      "Forward",
      "Guard",
    },
  }
  playerID = model.ArgString{
    Name: "PlayerID",
    Default: "0",
  }
  playerOrTeam = model.ArgEnum{
    Name:    "PlayerOrTeam",
    Options: []string{"T", "P"},
  }
  plusMinus = model.ArgEnum{
    Name:    "PlusMinus",
    Default: "N",
    Options: []string{"Y", "N"},
  }
  rank = model.ArgEnum{
    Name: "Rank",
    Default: "N",
    Options: []string{"Y", "N"},
  }
  season = model.ArgEnum{
    Name:    "Season",
    Default: "2020-21",
    Options: []string{
      "2020-21",
      "2019-20",
      "2018-19",
      "2017-18",
      "2016-17",
      "2015-16",
      "2014-15",
      "2013-14",
      "2012-13",
      "2011-12",
      "2010-11",
      "2009-10",
      "2008-09",
      "2007-08",
      "2006-07",
      "2005-06",
      "2004-05",
      "2003-04",
      "2002-03",
      "2001-02",
      "2000-01",
      "1999-00",
      "1998-99",
      "1997-98",
      "1996-97",
    },
  }
  seasonSegment = model.ArgEnum{
    Name:    "SeasonSegment",
    Options: []string{
      "Pre All-Star",
      "Post All-Star",
    },
  }
  seasonType = model.ArgEnum{
    Name:    "SeasonType",
    Default: "Regular Season",
    Options: []string{
      "Pre Season",
      "Regular Season",
      "Playoffs",
      "All Star",
    },
  }
  shotClockRange = model.ArgEnum{
    Name:    "ShotClockRange",
    Options: []string{
      "24-22",
      "22-18 Very Early",
      "18-15 Early",
      "15-7 Average",
      "7-4 Late",
      "4-0 Very Late",
      "ShotClock Off",
    },
  }
  sorter = model.ArgEnum{
    Name: "Sorter",
    Default: "DATE",
    Options: []string{"DATE"},
  }
  split = model.ArgEnum{
    Name:    "Split",
    Default: "general",
    Options: []string{"general"},
  }
  starterBench = model.ArgEnum{
    Name:    "StarterBench",
    Options: []string{
      "Starters",
      "Bench",
    },
  }
  startPeriod = model.ArgInt{
    Name:    "StartPeriod",
    Min:     model.IntPtr(0),
    Max:     model.IntPtr(4),
  }
  teamID = model.ArgString{
    Name:    "TeamID",
    Default: "0",
  }
  twoWay = model.ArgInt{
    Name: "TwoWay",
    Min:  model.IntPtr(0),
    Max:  model.IntPtr(1),
  }
  vsConference = model.ArgEnum{
    Name:    "VsConference",
    Options: []string{"East", "West"},
  }
  vsDivision = model.ArgEnum{
    Name:    "VsDivision",
    Options: []string{
      "Atlantic",
      "Central",
      "Northwest",
      "Pacific",
      "Southeast",
      "Southwest",
      "East",
      "West",
    },
  }
  weight = model.ArgEnum{
    Name:    "Weight",
    Options: []string{
      "< 200",
      "> 200",
      "< 225",
      "> 225",
      "< 250",
      "> 250",
      "< 275",
      "> 275",
      "< 300",
      "> 300",
    },
  }
)
